using ArchitectureLibrary.Model;
using GBATool.Enums;
using GBATool.FileSystem;
using GBATool.Models;
using GBATool.Utils;
using GBATool.VOs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace GBATool.Building;

public sealed class BuildPalettesFasmarm : Building<BuildPalettesFasmarm>
{
    private static readonly string FileName = "palettes.asm";
    private string[]? _outputPaths;

    protected override OutputFormat OutputFormat { get; } = OutputFormat.Fasmarm;
    protected override string[] OutputPaths
    {
        get
        {
            if (_outputPaths == null)
            {
                _outputPaths = new string[1];
                ProjectModel projectModel = ModelManager.Get<ProjectModel>();
                _outputPaths[0] = projectModel.Build.GeneratedSourcePath;
            }

            return _outputPaths;
        }
    }

    protected override async Task<bool> DoGenerate()
    {
        string filePath = Path.Combine(OutputPaths[0], FileName);

        using StreamWriter outputFile = new(filePath);

        List<FileModelVO> paletteModelVOs = ProjectFiles.GetModels<PaletteModel>();

        List<string> header = Util.GetAutoGeneratedHeaderInfo(";");
        foreach (string item in header)
        {
            outputFile.WriteLine(item);
        }
        outputFile.Write(Environment.NewLine);
        outputFile.WriteLine("; Color format: RGB555 0BBBBBGGGGGRRRRR");

        SortedDictionary<string, int[]> pals = [];

        int processedCount = 0;

        foreach (FileModelVO vo in paletteModelVOs)
        {
            if (vo.Model is not PaletteModel model)
            {
                continue;
            }

            if (model == null)
            {
                continue;
            }

            string? name = PaletteUtils.GetPaletteName(vo);

            if (string.IsNullOrEmpty(name))
            {
                continue;
            }

            pals.Add(name, model.Colors);

            processedCount++;
        }

        if (processedCount == 0)
        {
            AddError("No palettes processed");
        }
        else
        {
            await Task.Run(() => WritePalettesToOutputFile(ref pals, outputFile)).ConfigureAwait(false);
        }

        return true;
    }

    private static void WritePalettesToOutputFile(ref SortedDictionary<string, int[]> pals, StreamWriter outputFile)
    {
        outputFile.Write(Environment.NewLine);
        _ = outputFile.WriteLineAsync("    align 32");

        foreach (KeyValuePair<string, int[]> palette in pals)
        {
            int cont = 0;

            outputFile.WriteLine($"{palette.Key}:");
            outputFile.Write($"    db ");

            foreach (int item in palette.Value)
            {
                System.Windows.Media.Color color = PaletteUtils.GetColorFromInt(item);

                ushort rgb555 = (ushort)(((color.B & 0xF8) << 7) | ((color.G & 0xF8) << 2) | (color.R >> 3));

                byte[] bytes = BitConverter.GetBytes(rgb555);

                outputFile.Write($"0x{bytes[0]:X2},0x{bytes[1]:X2}");

                cont++;

                if (cont % 16 > 0)
                    outputFile.Write(",");
                else
                    outputFile.Write(Environment.NewLine);
            }
        }

        outputFile.Write(Environment.NewLine);
    }
}
