using ArchitectureLibrary.Model;
using GBATool.Enums;
using GBATool.FileSystem;
using GBATool.Models;
using GBATool.Utils;
using GBATool.VOs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace GBATool.Building;

public sealed class BuildMapsFasmarm : Building<BuildMapsFasmarm>
{
    private string[]? _outputPaths;
    protected override OutputFormat OutputFormat { get; } = OutputFormat.Fasmarm;
    protected override string[] OutputPaths
    {
        get
        {
            if (_outputPaths == null)
            {
                _outputPaths = new string[1];
                ProjectModel projectModel = ModelManager.Get<ProjectModel>();
                _outputPaths[0] = projectModel.Build.GeneratedSourcePath;
            }

            return _outputPaths;
        }
    }

    protected override async Task<bool> DoGenerate()
    {
        List<FileModelVO> models = ProjectFiles.GetModels<MapModel>();

        foreach (FileModelVO item in models)
        {
            if (item.Model is not MapModel model)
            {
                continue;
            }

            if (string.IsNullOrEmpty(item.Name))
            {
                continue;
            }

            string parentFolder = Util.GetAbsolutePathFromRelativeToProject(OutputPaths[0]);

            using StreamWriter outputFile = new(Path.Combine(parentFolder, item.Name + ".asm"));

            await WriteMaps(outputFile, model, item.Name.Replace(' ', '_'));
        }

        return GetErrors().Length == 0;
    }

    private async Task WriteMaps(StreamWriter outputFile, MapModel model, string name)
    {
        List<string> header = Util.GetAutoGeneratedHeaderInfo(";");
        foreach (string item in header)
        {
            await outputFile.WriteLineAsync(item);
        }
        await outputFile.WriteAsync(Environment.NewLine);

        await outputFile.WriteLineAsync("    align 4");
        await outputFile.WriteLineAsync($"map_{name}:");

        foreach (Tile tile in model.Tiles)
        {
            TileSetModel? tileSetModel = ProjectFiles.GetModel<TileSetModel>(tile.TileSetID);

            if (tileSetModel == null)
            {
                continue;
            }

            int index = -1;

            for (int i = 0; i < tileSetModel.Sprites.Count; i++)
            {
                SpriteModel sprite = tileSetModel.Sprites[i]; 

                if (sprite.ID == tile.SpriteTileID)
                {
                    index = i;
                    break;
                }
            }

            if (index == -1)
            {
                continue;
            }

            ushort tileIndex = (ushort)(index & 1023); // 1023 = 0000 0011 1111 1111b
            ushort horizontalFlip = (ushort)(tile.FlipHorizontal ? 1024 : 0); // 1023 = 0000 0100 0000 0000b
            ushort verticalFlip = (ushort)(tile.FlipVertical ? 2048 : 0); // 2048 = 0000 1000 0000 0000
            ushort paletteIndex = (ushort)(ushort.Clamp((ushort)tile.PaletteIndex, 0, 16) << 12);

            ushort tileValue = (ushort)(paletteIndex | verticalFlip | horizontalFlip | tileIndex);

            await outputFile.WriteLineAsync($"    db 0x{tileValue:X4}");
        }
    }
}
