using ArchitectureLibrary.Model;
using GBATool.Enums;
using GBATool.FileSystem;
using GBATool.Models;
using GBATool.Utils;
using GBATool.VOs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

// Information taken from pages:
// - https://gbadev.net/gbadoc/registers.html#REG_BGCNT
// - https://gbadev.net/gbadoc/backgrounds.html

namespace GBATool.Building;

public sealed class BuildMapsFasmarm : Building<BuildMapsFasmarm>
{
    private readonly string[] _outputPaths = new string[1];
    protected override OutputFormat OutputFormat { get; } = OutputFormat.Fasmarm;
    protected override string[] OutputPaths
    {
        get
        {
            ProjectModel projectModel = ModelManager.Get<ProjectModel>();
            _outputPaths[0] = projectModel.Build.GeneratedSourcePath;

            return _outputPaths;
        }
    }

    protected override async Task<bool> DoGenerate()
    {
        List<FileModelVO> models = ProjectFiles.GetModels<MapModel>();

        foreach (FileModelVO item in models)
        {
            if (item.Model is not MapModel model)
            {
                continue;
            }

            if (string.IsNullOrEmpty(item.Name))
            {
                continue;
            }

            string name = item.Name.Replace(' ', '_').ToLower();

            if (string.IsNullOrEmpty(model.BankID))
            {
                AddWarning($"Maps, {name}, doesnt have a bank id associated with it. Skip it");
                continue;
            }

            if (model.MapType == MapType.Affine)
            {
                AddWarning($"Affine maps, {name}, are not supported yet.");
                continue;
            }

            FileModelVO? fileModelBankVO = ProjectFiles.GetFileModel(model.BankID);

            if (fileModelBankVO == null || string.IsNullOrEmpty(fileModelBankVO.Name))
            {
                continue;
            }

            BankModel? bankModel = ProjectFiles.GetModel<BankModel>(model.BankID);

            if (bankModel == null)
            {
                continue;
            }

            if (bankModel.BitsPerPixel == BitsPerPixel.f1bpp)
            {
                AddWarning($"Bank in map {name} has 1bpp set so it is skipped.");
                continue;
            }

            string bankName = fileModelBankVO.Name;

            string parentFolder = Util.GetAbsolutePathFromRelativeToProject(OutputPaths[0]);

            using StreamWriter outputFile = new(Path.Combine(parentFolder, name + ".asm"));

            await WriteMaps(outputFile, model, name, bankModel, bankName);

            using StreamWriter literalPoolOutputFile = new(Path.Combine(parentFolder, "literal_pool_" + name + ".asm"));

            await WriteLiteralPoolFile(literalPoolOutputFile, name);
        }

        return GetErrors().Length == 0;
    }

    private static async Task WriteMaps(StreamWriter outputFile, MapModel model, string name, BankModel bankModel, string bankName)
    {
        List<string> header = Util.GetAutoGeneratedHeaderInfo(";");
        foreach (string item in header)
        {
            await outputFile.WriteLineAsync(item);
        }
        await outputFile.WriteAsync(Environment.NewLine);

        await outputFile.WriteLineAsync("    align 4");
        await outputFile.WriteLineAsync($"map_{name}_config_table:");

        string mapColorDepth = bankModel.BitsPerPixel == BitsPerPixel.f8bpp ? "0000000010000000b" : "0000000000000000b";
        string screenBaseBlock = Util.ConvertShortToBits((short)model.ScreenBaseBlock, 8) + "b";

        string characterBaseBlock = model.CharacterBaseBlock switch
        {
            CharacterBaseBlock.Block3 => "0000000000001100b",
            CharacterBaseBlock.Block2 => "0000000000001000b",
            CharacterBaseBlock.Block1 => "0000000000000100b",
            _ => "0000000000000000b"
        };

        string characterBaseBlockAddress = model.CharacterBaseBlock switch
        {
            CharacterBaseBlock.Block3 => "0x0600C000",
            CharacterBaseBlock.Block2 => "0x06008000",
            CharacterBaseBlock.Block1 => "0x06004000",
            _ => "0x06000000"
        };

        string mapSize;

        if (model.MapType == MapType.Regular)
        {
            mapSize = model.BckgrRegularSize switch
            {
                BckgrRegularSize.Regular64x64 => "1100000000000000b",
                BckgrRegularSize.Regular32x64 => "1000000000000000b",
                BckgrRegularSize.Regular64x32 => "0100000000000000b",
                _ => "0000000000000000b" // 32x32
            };
        }
        else
        {
            mapSize = model.BckgrAffineSize switch
            {
                BckgrAffineSize.Affine128x128 => "1100000000000000b",
                BckgrAffineSize.Affine64x64 => "1000000000000000b",
                BckgrAffineSize.Affine32x32 => "0100000000000000b",
                _ => "0000000000000000b" // 16x16
            };
        }   

        string mapPriority = model.Priority switch
        {
            Priority.Lowest => "0000000000000011b",
            Priority.Low => "0000000000000010b",
            Priority.High => "0000000000000001b",
            _ => "0000000000000000b"
        };

        await outputFile.WriteLineAsync("    ; background configuration");
        await outputFile.WriteLineAsync("    ; Character base block      Map size             Color depth         Map priority        Screen base block");
        await outputFile.WriteLineAsync($"    dh ({characterBaseBlock} or {mapSize} or {mapColorDepth} or {mapPriority} or {screenBaseBlock})");
        await outputFile.WriteLineAsync("    ; Padding");
        await outputFile.WriteLineAsync("    dh 0x0000");
        await outputFile.WriteLineAsync("    ; pointer to the tilesets");
        await outputFile.WriteLineAsync($"    dw Block_{bankName.ToLower()}");
        await outputFile.WriteLineAsync("    ; character base block destination address");
        await outputFile.WriteLineAsync($"    dw {characterBaseBlockAddress}");
        await outputFile.WriteLineAsync("    ; size in bytes of the block used by this frame");
        await outputFile.WriteLineAsync($"    dw Size_block_{bankName.ToLower()}");
        await outputFile.WriteLineAsync("    ; size of the map data");
        await outputFile.WriteLineAsync($"    dw (__map_{name} - map_{name})");
        await outputFile.WriteLineAsync("    ; map pointer");
        await outputFile.WriteLineAsync($"    dw map_{name}");

        await outputFile.WriteAsync(Environment.NewLine);

        await outputFile.WriteLineAsync("    align 2");
        await outputFile.WriteLineAsync($"map_{name}:");

        if (model.MapType == MapType.Regular)
        {
            if (model.BckgrRegularSize == BckgrRegularSize.Regular32x32)
            {
                await WriteMapTiles(outputFile, model.Tiles0);
            }
            else if (model.BckgrRegularSize == BckgrRegularSize.Regular32x64)
            {
                await WriteMapTiles(outputFile, model.Tiles0);
                await WriteMapTiles(outputFile, model.Tiles2);
            }
            else if (model.BckgrRegularSize == BckgrRegularSize.Regular64x32)
            {
                await WriteMapTiles(outputFile, model.Tiles0);
                await WriteMapTiles(outputFile, model.Tiles1);
            }
            else if (model.BckgrRegularSize == BckgrRegularSize.Regular64x64)
            {
                await WriteMapTiles(outputFile, model.Tiles0);
                await WriteMapTiles(outputFile, model.Tiles1);
                await WriteMapTiles(outputFile, model.Tiles2);
                await WriteMapTiles(outputFile, model.Tiles3);
            }
        }
        else
        {
            int size = model.BckgrAffineSize switch
            {
                BckgrAffineSize.Affine128x128 => 128*128,
                BckgrAffineSize.Affine64x64 => 64*64,
                BckgrAffineSize.Affine32x32 => 32*32,
                _ => 16*16
            };

            Tile[] tiles = new Tile[size];
            Array.Copy(model.AffineTiles.ToArray(), tiles, size);
            await WriteMapTiles(outputFile, tiles);
        }

        await outputFile.WriteAsync(Environment.NewLine);
        await outputFile.WriteLineAsync($"__map_{name}:");
    }

    private static async Task WriteMapTiles(StreamWriter outputFile, Tile[] mapTiles)
    {
        int countHexValues = 0;

        foreach (Tile tile in mapTiles)
        {
            TileSetModel? tileSetModel = ProjectFiles.GetModel<TileSetModel>(tile.TileSetID);

            if (tileSetModel == null)
            {
                continue;
            }

            if (!tileSetModel.GetSpriteIndex(tile.SpriteTileID, out int spriteIndex))
            {
                continue;
            }

            ushort tileIndex = (ushort)(spriteIndex & 1023); // 1023 = 0000 0011 1111 1111b
            ushort horizontalFlip = (ushort)(tile.FlipHorizontal ? 1024 : 0); // 1023 = 0000 0100 0000 0000b
            ushort verticalFlip = (ushort)(tile.FlipVertical ? 2048 : 0); // 2048 = 0000 1000 0000 0000
            ushort paletteIndex = (ushort)(ushort.Clamp(tile.PaletteIndex, 0, 16) << 12);

            ushort tileValue = (ushort)(paletteIndex | verticalFlip | horizontalFlip | tileIndex);

            if (countHexValues % 32 == 0)
            {
                if (countHexValues > 0)
                {
                    await outputFile.WriteAsync(Environment.NewLine);
                }   

                await outputFile.WriteAsync($"    dh 0x{tileValue:X4},");
            }
            else
            {
                await outputFile.WriteAsync($"0x{tileValue:X4}");

                if (countHexValues % 32 < 31 && countHexValues != mapTiles.Length - 1)
                {
                    await outputFile.WriteAsync(',');
                }
            }

            countHexValues++;
        }
    }

    private static async Task WriteLiteralPoolFile(StreamWriter outputFile, string name)
    {
        List<string> header = Util.GetAutoGeneratedHeaderInfo(";");
        foreach (string item in header)
        {
            await outputFile.WriteLineAsync(item);
        }
        await outputFile.WriteAsync(Environment.NewLine);
        await outputFile.WriteLineAsync("    align 4");
        await outputFile.WriteLineAsync($"Map{name.ToCamelCase()}ConfigTable:");
        await outputFile.WriteLineAsync($"    dw map_{name}_config_table");
    }
}
