using ArchitectureLibrary.Model;
using GBATool.Enums;
using GBATool.FileSystem;
using GBATool.Models;
using GBATool.Utils;
using GBATool.VOs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media;

namespace GBATool.Building;

public sealed class BuildPalettesButano : Building<BuildPalettesButano>
{
    protected override string FileName { get; } = string.Empty;
    protected override OutputFormat OutputFormat { get; } = OutputFormat.Butano;
    private readonly List<string> _palettesAlreadyWritten = [];

    protected override async Task<bool> DoGenerate()
    {
        ProjectModel projectModel = ModelManager.Get<ProjectModel>();

        string outputPath = Path.GetFullPath(projectModel.Build.GeneratedAssetsPath);

        List<FileModelVO> paletteModelVOs = ProjectFiles.GetModels<PaletteModel>();

        SortedDictionary<string, PaletteModel> pals = [];

        _palettesAlreadyWritten.Clear();

        int processedCount = 0;

        string folderPalettesKey = "folderPalettes";
        string folderPalettes = (string)Application.Current.FindResource(folderPalettesKey);

        foreach (FileModelVO vo in paletteModelVOs)
        {
            if (vo.Model is not PaletteModel model)
            {
                continue;
            }

            if (model == null)
            {
                continue;
            }

            if (string.IsNullOrEmpty(vo.Name))
            {
                continue;
            }

            if (string.IsNullOrEmpty(vo.Path))
            {
                continue;
            }

            string[] array = vo.Path.Split(Path.DirectorySeparatorChar);
            int index = Array.IndexOf(array, folderPalettes);

            StringBuilder sb = new();
            for (int i = index + 1; i < array.Length; i++)
            {
                sb.Append(array[i]);
                sb.Append('_');
            }

            string name = $"palette_{sb}{vo.Name.Replace(' ', '_').ToLower()}";

            pals.Add(name, model);

            processedCount++;
        }

        if (processedCount == 0)
        {
            AddError("No palettes processed");
        }
        else
        {
            foreach (KeyValuePair<string, PaletteModel> palette in pals)
            {
                if (_palettesAlreadyWritten.Exists(x => x == palette.Value.GUID))
                {
                    continue;
                }

                string name = palette.Key;
                int paletteArraySize = 16;

                if (palette.Value.LinkedPalettes.Count > 0)
                {
                    string remove = "_Palette_XX";

                    name = name.Replace(name[^remove.Length..], string.Empty); // Removes the "_Palette_XX" from the name
                    paletteArraySize = palette.Value.LinkedPalettes.Count * 16;
                }

                string filePath = Path.Combine(outputPath, $"{name}.h");

                using StreamWriter outputFile = new(filePath);

                await WriteHeader(outputFile, name);
                await WritePalettesToOutputFile(outputFile, palette.Value, name, paletteArraySize);
                await WriteFooter(outputFile, name);
            }
        }

        return true;
    }

    private static async Task WriteHeader(StreamWriter outputFile, string name)
    {
        List<string> header = Util.GetAutoGeneratedHeaderInfo("//");

        foreach (string item in header)
        {
            await outputFile.WriteLineAsync(item);
        }

        await outputFile.WriteAsync(Environment.NewLine);

        await outputFile.WriteLineAsync($"#ifndef GBATOOL_{name.ToUpper()}");
        await outputFile.WriteLineAsync($"#define GBATOOL_{name.ToUpper()}");

        await outputFile.WriteAsync(Environment.NewLine);

        await outputFile.WriteLineAsync("#include \"bn_sprite_item.h\"");

        await outputFile.WriteAsync(Environment.NewLine);
    }

    private static async Task WriteFooter(StreamWriter outputFile, string name)
    {
        await outputFile.WriteLineAsync($"#endif // GBATOOL_{name.ToUpper()}");
    }

    private async Task WritePalettesToOutputFile(StreamWriter outputFile, PaletteModel model, string name, int paletteArraySize)
    {
        await outputFile.WriteLineAsync($"#define {name}Len {paletteArraySize * 2}");
        await outputFile.WriteLineAsync($"const bn::color {name}Pal[{paletteArraySize}] =");
        await outputFile.WriteLineAsync("{");

        if (model.LinkedPalettes.Count > 0)
        {
            int countPalettes = 0;

            foreach (string id in model.LinkedPalettes)
            {
                PaletteModel? linkedModel = ProjectFiles.GetModel<PaletteModel>(id);

                if (linkedModel != null)
                {
                    await WriteColors(outputFile, linkedModel.Colors);

                    _palettesAlreadyWritten.Add(linkedModel.GUID);
                }

                countPalettes++;

                if (countPalettes <= model.LinkedPalettes.Count)
                {
                    if (countPalettes < model.LinkedPalettes.Count)
                        await outputFile.WriteAsync(",");

                    await outputFile.WriteAsync(Environment.NewLine);
                }
            }
        }
        else
        {
            await WriteColors(outputFile, model.Colors);
            await outputFile.WriteAsync(Environment.NewLine);
        }

        await outputFile.WriteLineAsync("};");
        await outputFile.WriteAsync(Environment.NewLine);
    }

    private static async Task WriteColors(StreamWriter outputFile, int[] colors)
    {
        int cont = 0;

        foreach (int item in colors)
        {
            Color color = PaletteUtils.GetColorFromInt(item);

            ushort rgb555 = (ushort)(((color.B & 0xF8) << 7) | ((color.G & 0xF8) << 2) | (color.R >> 3));

            if (cont % 16 == 0)
            {
                await outputFile.WriteAsync("    ");
            }

            await outputFile.WriteAsync($"bn::color(0x{rgb555:X4})");

            cont++;

            if (cont % 16 > 0)
            {
                await outputFile.WriteAsync(", ");
            }
        }
    }
}
